#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""一键脚本：构建 STM32F407 发布固件 + Renode 双分区运行 + Rust 集成测试(intg) 自动验证。

完整复现 F407 rel (Track B) 验证流程：
  1) RTOS 发布固件构建  : build_rel.bat
                         (RTOS_SELFTEST=OFF, -DRUST_APP_LIB= 空 -> 双分区 Track B,
                          JOC_RENODE=1 -> RENODE 构建)
                         产出 build_rel/stm32f407_minimal.elf / .bin
  2) Rust App 集成测试构建: ../joc-app-rust/build_app.py --features integration-test -> app.bin
  3) Renode 双分区运行  : 生成临时 resc（等价 tools/renode/stm32f407_jos_intg.resc）:
                         firmware ELF @0x08000000 + app.bin @0x08060000
                         （真实场景：app 与 rtos 固件分别烧录到不同分区）
  4) 自动验证           : tools/renode/verify_app.py <log> --mode=intg
                         （boot + 11 个 INTG marker + 无 fault）

用法:
  python build_rel_intg.py                # 全量：构建 + 运行(~120s) + 验证
  python build_rel_intg.py --no-build     # 跳过 RTOS/App 构建，直接用现有产物
  python build_rel_intg.py --seconds 60   # 自定义 Renode 运行秒数
  python build_rel_intg.py --mips 168     # 更贴近真实时序（默认 500）
  python build_rel_intg.py --keep-resc    # 保留生成的临时 resc 供调试

退出码: 0 = 全部通过; 1 = 任一环节失败。
"""
import argparse
import os
import subprocess
import sys
import time

# ---- 若被 MSYS/Git-Bash 的 posix Python 执行，改用原生 Windows Python 重跑自己 ----
# MSYS python 无法可靠 spawn 原生 Windows 进程（cmd /c 会挂起、renode.exe 报 '' 找不到），
# 因此检测到 posix 解释器时用 `py -3`（Windows 原生）再跑一遍本脚本。
if os.name != "nt":
    def _win_script_path(p):
        # /d/projects/... -> D:/projects/...
        if p and p[0] == "/" and len(p) > 2 and p[2] == "/":
            return p[1].upper() + ":" + p[2:]
        return p

    print("[rerun] 检测到 MSYS/Git-Bash Python，切换原生 Windows Python 执行...")
    sys.exit(subprocess.call(["py", "-3", _win_script_path(os.path.abspath(__file__))]
                             + sys.argv[1:]))

BASE = os.path.dirname(os.path.abspath(__file__))              # joc-base
APP_DIR = os.path.normpath(os.path.join(BASE, "..", "joc-app-rust"))
RENODE_TOOLS = os.path.join(BASE, "tools", "renode")

# ---- 路径配置（按本机环境，与 build_run_renode.py 风格一致）----
RENODE_EXE = r"D:\soft\Renode\renode.exe"
REPL       = os.path.join(RENODE_TOOLS, "stm32f4_jos.repl")
UART_HOOK  = os.path.join(RENODE_TOOLS, "uart_capture.py")
VERIFY_PY  = os.path.join(RENODE_TOOLS, "verify_app.py")
BUILD_REL  = os.path.join(BASE, "build_rel.bat")
BUILD_APP  = os.path.join(APP_DIR, "build_app.py")

SYS_ELF  = os.path.join(BASE, "build_rel", "stm32f407_minimal.elf")
APP_BIN  = os.path.join(APP_DIR, "app.bin")
APP_ADDR = "0x08060000"

LOG_PATH = os.path.join(BASE, "build_rel", "intg_run.log")     # Renode 全量输出
TMP_RESC = os.path.join(BASE, "build_rel", "_intg_tmp.resc")   # 生成的临时 resc


def win_path(p):
    """路径统一成 Renode 可识别的 Windows 盘符形式（D:/...）。"""
    p = os.path.abspath(p).replace("\\", "/")
    if p.startswith("/") and len(p) > 2 and p[2] == "/":
        p = p[1].upper() + ":" + p[2:]
    return p


def check_env():
    """前置检查：renode / 平台脚本 / 构建脚本 是否存在。"""
    for path, name in (
        (RENODE_EXE, "Renode"),
        (REPL, "平台描述 stm32f4_jos.repl"),
        (UART_HOOK, "UART 捕获 hook uart_capture.py"),
        (VERIFY_PY, "验证脚本 verify_app.py"),
        (BUILD_REL, "build_rel.bat"),
        (BUILD_APP, "build_app.py"),
    ):
        if not os.path.exists(path):
            print(f"[ERR] 未找到{name}: {path}", file=sys.stderr)
            sys.exit(1)


def build_rtos():
    """1/3 构建 RTOS 发布固件（Track B，走 build_rel.bat 保持配置单一来源）。"""
    print("[1/3] 构建 RTOS 发布固件 (build_rel.bat) ...")
    r = subprocess.run(["cmd", "/c", "build_rel.bat"], cwd=BASE)
    if r.returncode != 0:
        print("[ERR] build_rel.bat 构建失败", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(SYS_ELF):
        print(f"[ERR] 缺系统镜像: {SYS_ELF}", file=sys.stderr)
        sys.exit(1)


def build_app():
    """2/3 构建 Rust 集成测试 App（integration-test 特性 -> app.bin）。"""
    print("[2/3] 构建 Rust 集成测试 App (--features integration-test) ...")
    r = subprocess.run([sys.executable, "build_app.py",
                        "--features", "integration-test"], cwd=APP_DIR)
    if r.returncode != 0:
        print("[ERR] build_app.py 构建失败", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(APP_BIN):
        print(f"[ERR] 未找到构建产物: {APP_BIN}", file=sys.stderr)
        sys.exit(1)


def make_resc(mips, seconds):
    """生成临时 resc：镜像 tools/renode/stm32f407_jos_intg.resc（路径按实际计算）。"""
    lines = [
        "# generated by build_rel_intg.py (mirror of stm32f407_jos_intg.resc)",
        "mach create",
        f"machine LoadPlatformDescription @{win_path(REPL)}",
        f"include @{win_path(UART_HOOK)}",
        f"sysbus LoadELF @{win_path(SYS_ELF)}",
        f"sysbus LoadBinary @{win_path(APP_BIN)} {APP_ADDR}",
        f"cpu PerformanceInMips {mips}",
        "start",
        f"sleep {seconds}",
        "quit",
    ]
    with open(TMP_RESC, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def run_renode(seconds, mips):
    """3/3 启动 Renode（headless），stdout/stderr 重定向到 LOG_PATH。"""
    print(f"[3/3] Renode 双分区运行中（~{seconds}s @ {mips} MIPS）...")
    cmd = [RENODE_EXE, "--disable-xwt", "--console",
           "-e", f"include @{win_path(TMP_RESC)}"]
    timeout = seconds + 180   # sleep + 启动/退出余量
    t0 = time.time()
    try:
        with open(LOG_PATH, "w", encoding="utf-8", errors="replace") as f:
            subprocess.run(cmd, cwd=os.path.dirname(RENODE_EXE),
                           stdout=f, stderr=subprocess.STDOUT, timeout=timeout)
    except subprocess.TimeoutExpired:
        print(f"[ERR] Renode 运行超时（>{timeout}s），日志: {LOG_PATH}", file=sys.stderr)
        sys.exit(1)
    print(f"      完成，耗时 {time.time() - t0:.0f}s；日志: {LOG_PATH}")


def verify():
    """调 verify_app.py --mode=intg 做断言，返回是否全部通过。"""
    print("\n===== verify_app.py --mode=intg =====")
    r = subprocess.run([sys.executable, VERIFY_PY, LOG_PATH, "--mode=intg"])
    return r.returncode == 0


def main():
    ap = argparse.ArgumentParser(description="一键：F407 rel 构建 + Renode 双分区 + Rust intg 验证")
    ap.add_argument("--no-build", action="store_true",
                    help="跳过 RTOS/App 构建，直接用现有产物")
    ap.add_argument("--seconds", type=int, default=120, metavar="N",
                    help="Renode 运行秒数（默认 120）")
    ap.add_argument("--mips", type=int, default=500, metavar="N",
                    help="Renode 仿真速度 MIPS（默认 500）")
    ap.add_argument("--keep-resc", action="store_true",
                    help="保留生成的临时 resc 文件")
    args = ap.parse_args()

    check_env()

    if args.no_build:
        if not (os.path.exists(SYS_ELF) and os.path.exists(APP_BIN)):
            print("[ERR] --no-build 但缺产物（系统镜像或 app.bin），先全量跑一次", file=sys.stderr)
            sys.exit(1)
        print("[skip] 跳过构建（--no-build）")
    else:
        build_rtos()
        build_app()

    make_resc(args.mips, args.seconds)
    run_renode(args.seconds, args.mips)
    ok = verify()

    if not args.keep_resc and os.path.exists(TMP_RESC):
        os.remove(TMP_RESC)

    print("\n结果:", "PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
